[package]
name = "galital"
version = "2.0.0"
authors = ['Starkley Tech <contact@starkleytech.com>']
description = 'Galital substrate based node'
build = "build.rs"
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
default-run = "galital"
repository = 'https://github.com/starkleytech/galital'

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[badges]
travis-ci = { repository = "paritytech/substrate" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "paritytech/substrate" }
is-it-maintained-open-issues = { repository = "paritytech/substrate" }

[[bin]]
name = "galital"
# path = "./src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "2.0.0" }
serde = { version = "1.0.102", features = ["derive"] }
futures = { version = "0.3.9", features = ["compat"] }
hex-literal = "0.3.1"
log = "0.4.8"
rand = "0.7.2"
structopt = { version = "0.3.8" }
parking_lot = "0.11.1"

# primitives
sp-authority-discovery = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-consensus-babe = { version = "0.9.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
grandpa-primitives = { version = "3.0.0", package = "sp-finality-grandpa", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-core = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-runtime = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-timestamp = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-authorship = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-inherents = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master" }
sp-keyring = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-keystore = { version = "0.9.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-io = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-consensus = { version = "0.9.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-transaction-pool = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }

# client dependencies
sc-client-api = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-consensus = { version = "0.9.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-transaction-pool = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-network = { version = "0.9.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-consensus-slots = { version = "0.9.0", git = "https://github.com/starkleytech/substrate", branch = "master" }
sc-consensus-babe = { version = "0.9.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-consensus-uncles = { version = "0.9.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
grandpa = { version = "0.9.0", package = "sc-finality-grandpa", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-client-db = { version = "0.9.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-offchain = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-basic-authorship = { version = "0.9.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-service = { version = "0.9.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-tracing = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-telemetry = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-authority-discovery = { version = "0.9.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
jsonrpc-core = "15.1.0"
pallet-contracts-rpc = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-mmr-rpc = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-transaction-payment-rpc = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-consensus-babe-rpc = { version = "0.9.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-consensus-epochs = { version = "0.9.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-chain-spec = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-finality-grandpa-rpc = { version = "0.9.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-keystore = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-rpc-api = { version = "0.9.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-rpc = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master" }
sc-sync-state-rpc = { version = "0.9.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-api = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-block-builder = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-blockchain = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
substrate-frame-rpc-system = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }





# frame dependencies
pallet-indices = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-timestamp = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-contracts = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
frame-system = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-balances = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-transaction-payment = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
frame-support = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-im-online = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-authority-discovery = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-staking = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-grandpa = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master" }
frame-benchmarking = { version = "3.1.0", git = "https://github.com/starkleytech/substrate", branch = "master" }

# node-specific dependencies
galital-runtime = { version = "2.0.1", path = "../runtime" }
node-primitives = { version = "2.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
#node-executor = { version = "2.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }

# CLI-specific dependencies
sc-cli = { version = "0.9.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
frame-benchmarking-cli = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
node-inspect = { version = "0.8.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }

# WASM-specific dependencies
wasm-bindgen = { version = "0.2.73", optional = true }
wasm-bindgen-futures = { version = "0.4.18", optional = true }
browser-utils = { package = "substrate-browser-utils", git = "https://github.com/starkleytech/substrate", branch = "master" , optional = true, version = "0.9.0"}
libp2p-wasm-ext = { version = "0.28", features = ["websocket"], optional = true }

[target.'cfg(target_arch="x86_64")'.dependencies]
sc-executor = { version = "0.9.0", git = "https://github.com/starkleytech/substrate", branch = "master" , features = [ "wasmtime" ] }
sc-cli = { version = "0.9.0", optional = true, git = "https://github.com/starkleytech/substrate", branch = "master" , features = [ "wasmtime" ] }
sc-service = { version = "0.9.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master" , features = [ "wasmtime" ] }
sp-trie = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master" , features = ["memory-tracker"] }


[dev-dependencies]
sc-keystore = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
sc-service-test = { version = "2.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }
futures = "0.3.9"
tempfile = "3.1.0"
assert_cmd = "1.0"
nix = "0.19"
serde_json = "1.0"
regex = "1"
platforms = "1.1"
async-std = { version = "1.6.5", features = ["attributes"] }
soketto = "0.4.2"

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "master" }


[features]
default = []
runtime-benchmarks = [
	"galital-runtime/runtime-benchmarks",
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
