[package]
name = "galital-runtime"
version = "2.0.1"
authors = ['Starkley Tech <contact@starkleytech.com>']
edition = "2018"
build = "build.rs"
license = "Apache-2.0"
[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]



[build-dependencies]
substrate-wasm-builder = { version = "4.0.0", git = "https://github.com/starkleytech/substrate", branch = "master"  }

[dependencies]

# third-party dependencies
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
static_assertions = "1.1.0"
hex-literal = { version = "0.3.1", optional = true }
log = { version = "0.4.14", default-features = false }

# primitives
sp-authority-discovery = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-consensus-babe = { version = "0.9.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-block-builder = { git = "https://github.com/starkleytech/substrate", branch = "master" , default-features = false, version = "3.0.0"}
sp-inherents = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
node-primitives = { version = "2.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-offchain = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-core = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-std = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-api = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master" }
sp-runtime = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-staking = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-keyring = { version = "3.0.0", optional = true, git = "https://github.com/starkleytech/substrate", branch = "master" }
sp-session = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master" }
sp-transaction-pool = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-version = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
sp-npos-elections = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }

# frame dependencies
frame-executive = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
frame-benchmarking = { version = "3.1.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master" , optional = true }
frame-support = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
frame-system = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
frame-system-benchmarking = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master" , optional = true }
frame-system-rpc-runtime-api = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
frame-try-runtime = { version = "0.9.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master" , optional = true }
pallet-assets = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-authority-discovery = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-authorship = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-babe = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-balances = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-bounties = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master" }
pallet-collective = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-contracts = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-contracts-primitives = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-contracts-rpc-runtime-api = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master" }
pallet-democracy = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-election-provider-multi-phase = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-elections-phragmen = { version = "4.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master" }
pallet-gilt = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-grandpa = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-im-online = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-indices = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-identity = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master" }
pallet-lottery = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-membership = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-mmr = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-multisig = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master" }
pallet-offences = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-offences-benchmarking = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master" , default-features = false, optional = true }
pallet-proxy = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-randomness-collective-flip = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-recovery = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master" }
pallet-session = { version = "3.0.0", features = ["historical"], git = "https://github.com/starkleytech/substrate", branch = "master" , default-features = false }
pallet-session-benchmarking = { version = "3.0.0", git = "https://github.com/starkleytech/substrate", branch = "master" , default-features = false, optional = true }
pallet-staking = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-staking-reward-curve = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-scheduler = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-society = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-sudo = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-timestamp = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-tips = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-treasury = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-utility = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-transaction-payment = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }
pallet-transaction-payment-rpc-runtime-api = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master" }
pallet-vesting = { version = "3.0.0", default-features = false, git = "https://github.com/starkleytech/substrate", branch = "master"  }


# NFT dependencies
pallet-atomic-swap = { git = "https://github.com/starkleytech/substrate", branch = "master", default-features = false }
orml-nft = { git = "https://github.com/starkleytech/open-runtime-module-library", branch = "master", default-features = false }
nft-factory-pallet = { git = 'https://github.com/starkleytech/nft-factory-pallet', branch = 'master', default-features = false }

#Bridge
#chainbridge = { git = 'https://github.com/starkleytech/chainbridge-substrate', branch = 'main', default-features = false }
#bridge-pallet = { git = 'https://github.com/starkleytech/bridge-pallet', branch = 'main', default-features = false }




[features]
default = ["std"]
std = [
	"sp-authority-discovery/std",
	"pallet-assets/std",
	"pallet-authority-discovery/std",
	"pallet-authorship/std",
	"sp-consensus-babe/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-bounties/std",
	"sp-block-builder/std",
	"codec/std",
	"pallet-collective/std",
	"pallet-contracts/std",
	"pallet-contracts-primitives/std",
	"pallet-contracts-rpc-runtime-api/std",
	"pallet-democracy/std",
	"pallet-elections-phragmen/std",
	"frame-executive/std",
	"pallet-gilt/std",
	"pallet-grandpa/std",
	"pallet-im-online/std",
	"pallet-indices/std",
	"sp-inherents/std",
	"pallet-lottery/std",
	"pallet-membership/std",
	"pallet-mmr/std",
	"pallet-multisig/std",
	"pallet-identity/std",
	"pallet-scheduler/std",
	"node-primitives/std",
	"sp-offchain/std",
	"pallet-offences/std",
	"pallet-proxy/std",
	"sp-core/std",
	"pallet-randomness-collective-flip/std",
	"sp-std/std",
	"pallet-session/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-staking/std",
	"sp-keyring",
	"sp-session/std",
	"pallet-sudo/std",
	"frame-support/std",
	"frame-benchmarking/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-election-provider-multi-phase/std",
	"pallet-timestamp/std",
	"pallet-tips/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-treasury/std",
	"sp-transaction-pool/std",
	"pallet-utility/std",
	"sp-version/std",
	"pallet-society/std",
	"pallet-recovery/std",
	"pallet-vesting/std",
	"log/std",
	"frame-try-runtime/std",
	"sp-npos-elections/std",
	"pallet-atomic-swap/std",
	"orml-nft/std",
    'nft-factory-pallet/std',
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-election-provider-multi-phase/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-bounties/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"pallet-contracts/runtime-benchmarks",
	"pallet-democracy/runtime-benchmarks",
	"pallet-elections-phragmen/runtime-benchmarks",
	"pallet-gilt/runtime-benchmarks",
	"pallet-grandpa/runtime-benchmarks",
	"pallet-identity/runtime-benchmarks",
	"pallet-im-online/runtime-benchmarks",
	"pallet-indices/runtime-benchmarks",
	"pallet-lottery/runtime-benchmarks",
	"pallet-membership/runtime-benchmarks",
	"pallet-mmr/runtime-benchmarks",
	"pallet-multisig/runtime-benchmarks",
	"pallet-proxy/runtime-benchmarks",
	"pallet-scheduler/runtime-benchmarks",
	"pallet-society/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-tips/runtime-benchmarks",
	"pallet-treasury/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"pallet-vesting/runtime-benchmarks",
	"pallet-offences-benchmarking",
	"pallet-session-benchmarking",
	"frame-system-benchmarking",
]
